"""Internal Grok client for the xAI HTTPS API.

Import GrokClient and call the verbose methods on it, or use a resource
attribute when you want the calls grouped by endpoint family.
"""

from services.grok.builders import (
    assistant_text_message,
    audio_reference,
    chat_function_tool,
    chat_json_object_response_format,
    chat_json_schema_response_format,
    chat_live_search_tool,
    code_interpreter_tool,
    file_search_tool,
    image_generation_tool,
    image_reference,
    json_object_text_format,
    json_schema_text_format,
    live_search_parameters,
    mcp_server_tool,
    realtime_append_audio_message,
    realtime_cancel_response_message,
    realtime_clear_audio_message,
    realtime_commit_audio_message,
    realtime_conversation_item_message,
    realtime_create_response_message,
    realtime_session_update_message,
    responses_function_tool,
    speech_to_text_audio_done_message,
    speech_to_text_finalize_message,
    storage_options,
    system_text_message,
    text_to_speech_delta_message,
    text_to_speech_done_message,
    user_message_with_file,
    user_message_with_image,
    user_text_message,
    video_reference,
    web_search_tool,
    x_search_tool,
)
from services.grok.client import GrokClient, ServerStoredConversation
from services.grok.errors import (
    GrokApiError,
    GrokAuthenticationError,
    GrokConfigurationError,
    GrokError,
    GrokNotFoundError,
    GrokRateLimitError,
    GrokResponseTooLargeError,
    GrokSafetyError,
    GrokTimeoutError,
    GrokTransportError,
    GrokUsageError,
)
from services.grok.parsing import DeferredOperation
from services.grok.resources.realtime import EphemeralClientSecret
from services.grok.transport import ApiResult, WebsocketConnection

__all__ = [
    "ApiResult",
    "DeferredOperation",
    "EphemeralClientSecret",
    "GrokApiError",
    "GrokAuthenticationError",
    "GrokClient",
    "GrokConfigurationError",
    "GrokError",
    "GrokNotFoundError",
    "GrokRateLimitError",
    "GrokResponseTooLargeError",
    "GrokSafetyError",
    "GrokTimeoutError",
    "GrokTransportError",
    "GrokUsageError",
    "ServerStoredConversation",
    "WebsocketConnection",
    "assistant_text_message",
    "audio_reference",
    "chat_function_tool",
    "chat_json_object_response_format",
    "chat_json_schema_response_format",
    "chat_live_search_tool",
    "code_interpreter_tool",
    "file_search_tool",
    "image_generation_tool",
    "image_reference",
    "json_object_text_format",
    "json_schema_text_format",
    "live_search_parameters",
    "mcp_server_tool",
    "realtime_append_audio_message",
    "realtime_cancel_response_message",
    "realtime_clear_audio_message",
    "realtime_commit_audio_message",
    "realtime_conversation_item_message",
    "realtime_create_response_message",
    "realtime_session_update_message",
    "responses_function_tool",
    "speech_to_text_audio_done_message",
    "speech_to_text_finalize_message",
    "storage_options",
    "system_text_message",
    "text_to_speech_delta_message",
    "text_to_speech_done_message",
    "user_message_with_file",
    "user_message_with_image",
    "user_text_message",
    "video_reference",
    "web_search_tool",
    "x_search_tool",
]
