# Generated by Django 6.1.1 on 2026-09-26 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesale',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='marketplacesale',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=16),
        ),
        migrations.AlterField(
            model_name='marketplacesale',
            name='amount_minor',
            field=models.PositiveIntegerField(help_text='Seller proceeds for this sale, in minor currency units.'),
        ),
    ]
