# Generated by Django 6.1.1 on 2026-09-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiToken',
        ),
    ]
