# Generated by Django 6.1.1 on 2026-09-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_delete_apitoken'),
        ('payments', '0002_marketplacesale_listing_marketplacesale_status_and_more'),
    ]

    operations = [
    ]
