# Generated by Django 6.1.1 on 2026-09-26 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids'), ('unisex', 'Unisex')], max_length=32)),
                ('category', models.CharField(blank=True, choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('bags', 'Bags'), ('accessories', 'Accessories'), ('activewear', 'Activewear'), ('other', 'Other')], max_length=32)),
                ('garment_type', models.CharField(blank=True, max_length=64)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('colour', models.CharField(blank=True, max_length=64)),
                ('colour_secondary', models.CharField(blank=True, max_length=64)),
                ('size_label', models.CharField(blank=True, max_length=64)),
                ('size_system', models.CharField(blank=True, choices=[('uk', 'UK'), ('eu', 'EU'), ('us', 'US'), ('alpha', 'Alpha'), ('waist', 'Waist'), ('one_size', 'One size')], max_length=32)),
                ('condition', models.CharField(blank=True, choices=[('new_with_tags', 'New with tags'), ('new_without_tags', 'New without tags'), ('very_good', 'Very good'), ('good', 'Good'), ('satisfactory', 'Satisfactory')], max_length=32)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('flaws', models.TextField(blank=True)),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('inseam_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('package_size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=16)),
                ('cost_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('price_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('min_offer_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='gbp', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('listed', 'Listed'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('storage_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/')),
                ('position', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.item')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('item', 'position'), name='unique_item_photo_position')],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('vinted', 'Vinted'), ('depop', 'Depop'), ('ebay', 'eBay')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publishing', 'Publishing'), ('live', 'Live'), ('paused', 'Paused'), ('sold', 'Sold'), ('ended', 'Ended'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='gbp', max_length=3)),
                ('category_ref', models.CharField(blank=True, max_length=255)),
                ('shipping_price_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('listed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'marketplace'), name='unique_item_marketplace')],
            },
        ),
    ]
